# Generated by Django 4.1.2 on 2022-10-17 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0002_productdescription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productdescription',
            old_name='quatity',
            new_name='quantity',
        ),
    ]
