# Generated by Django 4.1.2 on 2022-10-17 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0003_rename_quatity_productdescription_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='product_key',
            field=models.ManyToManyField(blank=True, to='bill.productdescription'),
        ),
    ]
