# Generated by Django 4.1.2 on 2022-10-19 08:36

import bill.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0006_alter_bill_product_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_number',
            field=models.UUIDField(default=bill.models.bill_number, editable=False, unique=True),
        ),
    ]
